import Head from "next/head";
import styles from "../styles/Home.module.css";
import Entry from "../components/entry/Entry";
import ProjectList from "../components/projects/ProjectList";
import About from "../components/about/About";
import Tech from "../components/technologies/Tech";
import Courses from "../components/about/courses/Courses";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>OZalesskiy</title>
        <meta name="description" content="generated by me" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Entry />
        <ProjectList />
        <Tech />
        <About />
        {/* <Courses /> */}
      </main>
    </div>
  );
};

export default Home;
